# Generated by Django 5.1.15 on 2026-09-10 00:29

import apps.subscriptions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0003_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=120, unique=True)),
                ('type', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stripe event',
                'verbose_name_plural': 'Stripe events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Trial'), ('active', 'Active')], default='trialing', max_length=10, verbose_name='status')),
                ('trial_ends_at', models.DateTimeField(default=apps.subscriptions.models._fin_de_la_prueba, verbose_name='trial ends at')),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=120)),
                ('stripe_session_id', models.CharField(blank=True, default='', max_length=120)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='amount')),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='households.household')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
    ]
