# Generated by Django 5.1.15 on 2026-08-31 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='household name')),
                ('currency', models.CharField(default='CAD', max_length=3, verbose_name='currency')),
                ('timezone', models.CharField(default='America/Toronto', max_length=64, verbose_name='time zone')),
                ('budget_start_month', models.PositiveSmallIntegerField(default=1, verbose_name='budget start month')),
                ('family_size', models.PositiveSmallIntegerField(default=1, help_text='How many people live in the home. Not the same as how many use the app.', verbose_name='family size')),
                ('allowance_rollover', models.BooleanField(default=True, help_text='Unspent personal allowance carries into the next month.', verbose_name='allowance rolls over')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'household',
                'verbose_name_plural': 'households',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('member', 'Member')], default='member', max_length=10, verbose_name='role')),
                ('can_view_budget', models.BooleanField(default=True, verbose_name='can view the budget')),
                ('can_edit_budget', models.BooleanField(default=False, verbose_name='can edit the budget')),
                ('can_add_transactions', models.BooleanField(default=True, verbose_name='can add transactions')),
                ('can_view_reports', models.BooleanField(default=True, verbose_name='can view reports')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='households.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membership',
                'verbose_name_plural': 'memberships',
                'constraints': [models.UniqueConstraint(fields=('user', 'household'), name='una_membresia_por_usuario_y_hogar')],
            },
        ),
    ]
