# Generated by Django 5.1.15 on 2026-09-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0003_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français')], default='en', max_length=5, verbose_name='language'),
        ),
    ]
