# Generated by Django 5.1.15 on 2026-09-04 21:53

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0003_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='identifier')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='name')),
                ('is_system', models.BooleanField(default=False, verbose_name='preloaded')),
                ('kind', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=10, verbose_name='kind')),
                ('tax_category', models.CharField(blank=True, max_length=30, verbose_name='tax category')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='households.household')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='budget.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'abstract': False,
                'base_manager_name': 'unscoped',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('periodicity', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every two weeks'), ('semimonthly', 'Twice a month'), ('monthly', 'Monthly'), ('bimonthly', 'Every two months'), ('quarterly', 'Quarterly'), ('semiannual', 'Twice a year'), ('annual', 'Yearly')], max_length=20, verbose_name='how often')),
                ('effective_from', models.DateField(verbose_name='in effect from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='in effect until')),
                ('scope', models.CharField(choices=[('household', 'Household'), ('personal', 'Personal')], default='household', max_length=10, verbose_name='scope')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('is_essential', models.BooleanField(default=True, help_text='Essential expenses are the last ones a recommendation will touch.', verbose_name='essential')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_rules', to='budget.category')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='households.household')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_rules', to='households.membership')),
            ],
            options={
                'verbose_name': 'fixed expense',
                'verbose_name_plural': 'fixed expenses',
                'abstract': False,
                'base_manager_name': 'unscoped',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('periodicity', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every two weeks'), ('semimonthly', 'Twice a month'), ('monthly', 'Monthly'), ('bimonthly', 'Every two months'), ('quarterly', 'Quarterly'), ('semiannual', 'Twice a year'), ('annual', 'Yearly')], max_length=20, verbose_name='how often')),
                ('effective_from', models.DateField(verbose_name='in effect from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='in effect until')),
                ('scope', models.CharField(choices=[('household', 'Household'), ('personal', 'Personal')], default='household', max_length=10, verbose_name='scope')),
                ('source_type', models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('rental', 'Rental'), ('pension', 'Pension'), ('benefits', 'Benefits'), ('other', 'Other')], max_length=20, verbose_name='kind of income')),
                ('amount_type', models.CharField(choices=[('fixed', 'A fixed amount'), ('estimated', 'An amount I estimate each month'), ('range', 'A range — the budget uses the minimum'), ('rolling_average', 'The average of my last months'), ('irregular', 'Irregular — the budget counts zero')], max_length=20, verbose_name='how much')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='amount')),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='at least')),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='at most')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='households.household')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_sources', to='households.membership')),
            ],
            options={
                'verbose_name': 'income source',
                'verbose_name_plural': 'income sources',
                'abstract': False,
                'base_manager_name': 'unscoped',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='merchant')),
                ('normalized_name', models.CharField(editable=False, max_length=120)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='households.household')),
            ],
            options={
                'verbose_name': 'merchant',
                'verbose_name_plural': 'merchants',
                'abstract': False,
                'base_manager_name': 'unscoped',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('household', 'slug'), name='una_categoria_por_slug_y_hogar'),
        ),
        migrations.AddConstraint(
            model_name='merchant',
            constraint=models.UniqueConstraint(fields=('household', 'normalized_name'), name='un_comercio_por_nombre_y_hogar'),
        ),
    ]
