# Generated by Django 5.1.15 on 2026-09-04 22:27

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('households', '0003_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='year')),
                ('month', models.PositiveSmallIntegerField(verbose_name='month')),
                ('status', models.CharField(choices=[('future', 'Upcoming'), ('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10, verbose_name='status')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='households.household')),
            ],
            options={
                'verbose_name': 'budget month',
                'verbose_name_plural': 'budget months',
                'ordering': ['year', 'month'],
                'abstract': False,
                'base_manager_name': 'unscoped',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=10, verbose_name='kind')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='planned')),
                ('is_exceptional', models.BooleanField(default=False, verbose_name='one-off')),
                ('scope', models.CharField(choices=[('household', 'Household'), ('personal', 'Personal')], default='household', max_length=10, verbose_name='scope')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='budget.category')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='households.household')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='households.membership')),
                ('source_expense_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas', to='budget.expenserule')),
                ('source_income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas', to='budget.incomesource')),
                ('budget_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='budget.budgetmonth')),
            ],
            options={
                'verbose_name': 'budget line',
                'verbose_name_plural': 'budget lines',
                'abstract': False,
                'base_manager_name': 'unscoped',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresos_presupuestados', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ingresos_reales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('egresos_presupuestados', models.DecimalField(decimal_places=2, max_digits=12)),
                ('egresos_reales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('varianza_por_categoria', models.JSONField(default=dict)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('arrastre', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('budget_month', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cierre', to='budget.budgetmonth')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='households.household')),
            ],
            options={
                'verbose_name': 'monthly close',
                'verbose_name_plural': 'monthly closes',
                'abstract': False,
                'base_manager_name': 'unscoped',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('date', models.DateField(verbose_name='date')),
                ('payment_method', models.CharField(choices=[('debit', 'Debit card'), ('credit', 'Credit card'), ('cash', 'Cash'), ('transfer', 'Transfer'), ('other', 'Other')], default='debit', max_length=20, verbose_name='paid with')),
                ('scope', models.CharField(choices=[('household', 'Household'), ('personal', 'Personal')], default='household', max_length=10, verbose_name='scope')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='receipt')),
                ('budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='budget.budgetline')),
                ('budget_month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='budget.budgetmonth')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='budget.category')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='households.household')),
                ('income_source', models.ForeignKey(blank=True, help_text='Which income this belongs to, so its average can be computed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='budget.incomesource')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='households.membership')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='budget.merchant')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-date', '-pk'],
                'abstract': False,
                'base_manager_name': 'unscoped',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='budgetmonth',
            constraint=models.UniqueConstraint(fields=('household', 'year', 'month'), name='un_mes_por_hogar'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('source_income__isnull', True), ('source_expense_rule__isnull', True), _connector='OR'), name='una_linea_viene_de_una_sola_regla'),
        ),
    ]
