# Generated by Django 5.1.15 on 2026-09-05 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budgetmonth_budgetline_monthlyclose_transaction_and_more'),
        ('households', '0003_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetline',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lineas', to='budget.category'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lineas', to='households.membership'),
        ),
        migrations.AlterField(
            model_name='expenserule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='expense_rules', to='budget.category'),
        ),
        migrations.AlterField(
            model_name='expenserule',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='expense_rules', to='households.membership'),
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='income_sources', to='households.membership'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='budget_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transacciones', to='budget.budgetmonth'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transacciones', to='budget.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transacciones', to='households.membership'),
        ),
    ]
