# Generated by Django 5.1.15 on 2026-09-05 14:17

import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_budgetline_category_alter_budgetline_owner_and_more'),
        ('households', '0003_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='goal')),
                ('scope', models.CharField(choices=[('household', 'Household'), ('personal', 'Personal')], default='household', max_length=10, verbose_name='scope')),
                ('status', models.CharField(choices=[('active', 'Active'), ('reached', 'Reached'), ('abandoned', 'Abandoned')], default='active', max_length=10, verbose_name='status')),
                ('contribution_mode', models.CharField(choices=[('by_target_date', 'By a target date'), ('by_monthly_amount', 'By a monthly amount')], max_length=20, verbose_name='how to reach it')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='target amount')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='target date')),
                ('monthly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='monthly amount')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='households.household')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='goals', to='households.membership')),
            ],
            options={
                'verbose_name': 'goal',
                'verbose_name_plural': 'goals',
                'abstract': False,
                'base_manager_name': 'unscoped',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AllocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='priority')),
                ('target_type', models.CharField(choices=[('goal', 'A savings goal'), ('allowance', 'Personal allowance'), ('category', 'A category or fund')], max_length=12, verbose_name='goes to')),
                ('method', models.CharField(choices=[('fixed', 'A fixed amount'), ('percentage', 'A percentage of what is left over'), ('remainder', 'Everything that is left')], max_length=12, verbose_name='how much')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='amount')),
                ('percentage', models.DecimalField(blank=True, decimal_places=4, help_text='0.10 means ten percent of what is left over.', max_digits=5, null=True, verbose_name='percentage')),
                ('split', models.CharField(choices=[('equal', 'Equally'), ('weighted', 'By weights')], default='equal', max_length=10, verbose_name='split')),
                ('pesos', models.JSONField(blank=True, default=dict, help_text='Membership id to weight.')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='households.household')),
                ('target_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='allocation_rules', to='budget.category')),
                ('target_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocation_rules', to='budget.goal')),
            ],
            options={
                'verbose_name': 'split rule',
                'verbose_name_plural': 'split rules',
                'ordering': ['order'],
                'abstract': False,
                'base_manager_name': 'unscoped',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('date', models.DateField(verbose_name='date')),
                ('origen', models.CharField(choices=[('manual', 'Added by hand'), ('cascade', 'From the monthly split')], default='manual', max_length=10)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='budget.goal')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='households.household')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goal_contributions', to='households.membership')),
            ],
            options={
                'verbose_name': 'contribution',
                'verbose_name_plural': 'contributions',
                'ordering': ['-date', '-pk'],
                'abstract': False,
                'base_manager_name': 'unscoped',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='planned')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='actual')),
                ('budget_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='budget.budgetmonth')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='households.household')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asignaciones', to='households.membership')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asignaciones', to='budget.allocationrule')),
            ],
            options={
                'verbose_name': 'monthly split',
                'verbose_name_plural': 'monthly splits',
                'abstract': False,
                'base_manager_name': 'unscoped',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AllowanceLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='granted')),
                ('spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='spent')),
                ('adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='adjustment')),
                ('carried_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='carried in')),
                ('carried_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='carried out')),
                ('budget_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesadas', to='budget.budgetmonth')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='households.household')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mesadas', to='households.membership')),
            ],
            options={
                'verbose_name': 'allowance',
                'verbose_name_plural': 'allowances',
                'abstract': False,
                'base_manager_name': 'unscoped',
                'constraints': [models.UniqueConstraint(fields=('household', 'member', 'budget_month'), name='una_mesada_por_miembro_y_mes')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='allocationrule',
            constraint=models.UniqueConstraint(fields=('household', 'order'), name='un_orden_de_reparto_por_hogar'),
        ),
    ]
