# Generated by Django 5.1.15 on 2026-09-07 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_goal_allocationrule_goalcontribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcontribution',
            name='budget_month',
            field=models.ForeignKey(blank=True, help_text='Nulo si la fecha cae en un mes que el hogar no ha vivido.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='budget.budgetmonth'),
        ),
    ]
