# Generated by Django 5.1.15 on 2026-09-07 14:14

import django.db.models.deletion
from django.db import migrations, models


def _borrar_atribucion_falsa(apps, schema_editor):
    """Los aportes de cascada ya escritos llevan un miembro que no eligio nadie."""
    GoalContribution = apps.get_model("budget", "GoalContribution")
    GoalContribution.objects.filter(origen="cascade").update(member=None)


def _sin_vuelta_atras(apps, schema_editor):
    """No se puede: el miembro original era arbitrario, no hay a quien devolverselo."""


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_guardias_de_mes_cerrado'),
        ('households', '0003_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalcontribution',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Nulo cuando el aporte viene del reparto: ahorra el hogar, no una persona.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='goal_contributions', to='households.membership'),
        ),
        migrations.RunPython(_borrar_atribucion_falsa, _sin_vuelta_atras),
    ]
