# Generated by Django 5.1.15 on 2026-09-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_aporte_de_cascada_sin_miembro'),
        ('households', '0003_invitation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='monthlyallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', False)), fields=('household', 'budget_month', 'rule', 'member'), name='un_reparto_por_regla_y_miembro'),
        ),
        migrations.AddConstraint(
            model_name='monthlyallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', True)), fields=('household', 'budget_month', 'rule'), name='un_reparto_por_regla_sin_miembro'),
        ),
    ]
