# Generated by Django 5.1.15 on 2026-09-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_sembrar_catalogo_en_hogares_previos'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetline',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='due date'),
        ),
    ]
