# Generated by Django 5.1.15 on 2026-09-20 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_budgetline_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcontribution',
            name='counterpart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='budget.goalcontribution'),
        ),
        migrations.AddField(
            model_name='goalcontribution',
            name='note',
            field=models.CharField(blank=True, help_text='Where it came from, or what it went to.', max_length=200, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='contribution_mode',
            field=models.CharField(choices=[('by_target_date', 'By a target date'), ('by_monthly_amount', 'By a monthly amount'), ('open_fund', 'An open fund, no target')], max_length=20, verbose_name='how to reach it'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('reached', 'Reached'), ('abandoned', 'Abandoned'), ('archived', 'Archived')], default='active', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='target amount'),
        ),
        migrations.AlterField(
            model_name='goalcontribution',
            name='origen',
            field=models.CharField(choices=[('manual', 'Added by hand'), ('cascade', 'From the monthly split'), ('withdrawal', 'Withdrawal'), ('transfer_out', 'Transfer to another goal'), ('transfer_in', 'Transfer from another goal')], default='manual', max_length=12),
        ),
    ]
