# Generated by Django 5.1.15 on 2026-09-20 17:39

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_fondo_abierto_y_movimientos'),
        ('households', '0004_invitation_language_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('liquid', 'Cash and equivalents'), ('investment', 'Investments'), ('property', 'Property and real estate'), ('valuable', 'Valuables'), ('short_term', 'Short-term debt'), ('long_term', 'Long-term debt')], max_length=12, verbose_name='group')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='current value')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='households.household')),
            ],
            options={
                'verbose_name': 'balance item',
                'verbose_name_plural': 'balance items',
                'ordering': ['group', 'name'],
                'abstract': False,
                'base_manager_name': 'unscoped',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
